ref:
  as: optional-operators-configure-proxy-registry
  from: cli
  commands: optional-operators-configure-proxy-registry-commands.sh
  resources:
    requests:
      cpu: 300m
      memory: 300Mi
  env:
  - name: ENABLE_REDHAT_OPERATOR_CATALOG
    documentation: Optional. When set to true the redhat-operators catalog will be enabled.
    default: "false"
  credentials:
  - namespace: test-credentials # this entry injects the custom credential
    name: brew-registry-pullsecret
    mount_path: /var/run/brew-pullsecret
  documentation: |-
    The configure-proxy registry step configures the proxy image registry to pull internal images.
